spring.application.name=studymind
spring.datasource.url=jdbc:postgresql://localhost:5432/studymind
spring.datasource.username=postgres
spring.datasource.password=Vanda1107.

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration